// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointment.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAppointment = `-- name: CreateAppointment :one
WITH patient AS (
    INSERT INTO users (email, firstname, lastname, password_hash, role, verified)
    VALUES ($3, '', '', '', 'patient', false)
    ON CONFLICT (email) DO UPDATE
    SET role = CASE
            WHEN users.role = 'common' THEN 'patient'
            ELSE users.role
        END,
        updated_at = NOW()
    RETURNING id, email, role
)
INSERT INTO appointments (date, practitioner_id, patient_id)
SELECT $1, $2, patient.id
FROM patient
WHERE patient.role = 'patient'
RETURNING id, date, practitioner_id, patient_id, created_at, updated_at
`

type CreateAppointmentParams struct {
	Date           time.Time `json:"date"`
	PractitionerID uuid.UUID `json:"practitioner_id"`
	PatientEmail   string    `json:"patient_email"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment, arg.Date, arg.PractitionerID, arg.PatientEmail)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.PractitionerID,
		&i.PatientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
