// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: center.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getAllCenters = `-- name: GetAllCenters :many
SELECT id, name, street, street_number, city, postal_code, region, country, created_at, updated_at FROM centers
`

func (q *Queries) GetAllCenters(ctx context.Context) ([]Center, error) {
	rows, err := q.db.Query(ctx, getAllCenters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Center
	for rows.Next() {
		var i Center
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Street,
			&i.StreetNumber,
			&i.City,
			&i.PostalCode,
			&i.Region,
			&i.Country,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCenterByID = `-- name: GetCenterByID :one
SELECT id, name, street, street_number, city, postal_code, region, country, created_at, updated_at FROM centers
WHERE id = $1
`

func (q *Queries) GetCenterByID(ctx context.Context, id uuid.UUID) (Center, error) {
	row := q.db.QueryRow(ctx, getCenterByID, id)
	var i Center
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.StreetNumber,
		&i.City,
		&i.PostalCode,
		&i.Region,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
