// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO users (email, firstname, lastname, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, email, firstname, lastname, password_hash, role, verified, created_at, updated_at
`

type CreateParams struct {
	Email        string `json:"email"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (User, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Email,
		arg.Firstname,
		arg.Lastname,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.PasswordHash,
		&i.Role,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByEmail = `-- name: FindByEmail :one
SELECT id, email, firstname, lastname, password_hash, role, verified, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.PasswordHash,
		&i.Role,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByID = `-- name: FindByID :one
SELECT id, email, firstname, lastname, password_hash, role, verified, created_at, updated_at FROM users WHERE ID = $1
`

func (q *Queries) FindByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.PasswordHash,
		&i.Role,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUserByID = `-- name: VerifyUserByID :exec
UPDATE users
SET verified = true
WHERE id = $1
`

func (q *Queries) VerifyUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserByID, id)
	return err
}
