// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_code.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerificationCode = `-- name: CreateVerificationCode :exec
INSERT INTO verification_codes (user_id, code, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, code, expires_at, created_at
`

type CreateVerificationCodeParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, createVerificationCode, arg.UserID, arg.Code, arg.ExpiresAt)
	return err
}

const deleteVerificationCode = `-- name: DeleteVerificationCode :exec
DELETE FROM verification_codes
WHERE id = $1
`

func (q *Queries) DeleteVerificationCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationCode, id)
	return err
}

const getVerificationCode = `-- name: GetVerificationCode :one
SELECT id, user_id, code, expires_at, created_at FROM verification_codes
WHERE user_id = $1
`

func (q *Queries) GetVerificationCode(ctx context.Context, userID uuid.UUID) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerificationCode, userID)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
